development:
  address: "smtp.gmail.com"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name:
  password:
  enable_starttls_auto: true

production:
  address: "smtp.gmail.com"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: jcskyting@gmail.com
  password: Wedd0606
  enable_starttls_auto: true